pub mod events;

use std::sync::Mutex;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

use serde::Serialize;
use tauri::{AppHandle, Emitter};
use tauri_plugin_shell::ShellExt;
use tauri_plugin_shell::process::CommandChild;

use crate::config::settings;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ProxyStatus {
    Running,
    Stopped,
    Starting,
    Restarting,
    Crashed,
}

#[derive(Debug, Clone, Serialize)]
pub struct ProxyStatusEvent {
    pub status: ProxyStatus,
    pub port: u16,
    pub error: Option<String>,
}

pub struct ProxyState {
    child: Option<CommandChild>,
    pub port: u16,
    pub status: ProxyStatus,
    health_task_abort: Option<tokio::sync::oneshot::Sender<()>>,
    /// Shared flag set to `true` just before intentionally killing the process.
    /// The background watcher reads this to distinguish graceful stop from crash.
    stopping_flag: Arc<AtomicBool>,
}

impl Default for ProxyState {
    fn default() -> Self {
        Self {
            child: None,
            port: 8317,
            status: ProxyStatus::Stopped,
            health_task_abort: None,
            stopping_flag: Arc::new(AtomicBool::new(false)),
        }
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Build a `ProxyStatusEvent` snapshot from the current state (must already hold the lock).
fn snapshot(state: &ProxyState) -> ProxyStatusEvent {
    ProxyStatusEvent {
        status: state.status.clone(),
        port: state.port,
        error: None,
    }
}

/// Emit a "proxy-status-changed" event to all frontend windows.
fn emit_status(app_handle: &AppHandle, event: ProxyStatusEvent) {
    if let Err(e) = app_handle.emit("proxy-status-changed", event) {
        log::warn!("Failed to emit proxy-status-changed: {}", e);
    }
}

// ---------------------------------------------------------------------------
// Config generation
// ---------------------------------------------------------------------------

/// Generate a proxy-config.yaml for CLIProxyAPI in `~/.config/aether/`.
///
/// Returns the path to the generated config file.
fn generate_proxy_config(port: u16, management_key: &str) -> anyhow::Result<std::path::PathBuf> {
    // Use ~/.config/aether/ (not dirs::config_dir() which returns ~/Library/Application Support
    // on macOS — the space in that path breaks CLIProxyAPI's Go flag parser).
    let home = dirs::home_dir()
        .ok_or_else(|| anyhow::anyhow!("Could not find home directory"))?;
    let aether_dir = home.join(".config").join("aether");
    std::fs::create_dir_all(&aether_dir)?;

    let config_path = aether_dir.join("proxy-config.yaml");

    let auth_dir = aether_dir.join("auth");
    std::fs::create_dir_all(&auth_dir)?;
    let auth_dir_str = auth_dir
        .to_str()
        .ok_or_else(|| anyhow::anyhow!("Auth dir path contains invalid UTF-8"))?;

    // Minimal YAML config for CLIProxyAPI
    let yaml = format!(
        r#"# Auto-generated by Aether — do not edit manually
port: {}
auth-dir: "{}"
usage-statistics-enabled: true

remote-management:
  allow-remote: false
  secret-key: "{}"
  disable-control-panel: false
"#,
        port, auth_dir_str, management_key
    );

    std::fs::write(&config_path, yaml)?;
    log::info!("Generated proxy config at {:?}", config_path);

    Ok(config_path)
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Start the CLIProxyAPI sidecar on `port`.
///
/// Returns an error if the proxy is already running.
pub async fn start_proxy(
    app_handle: &AppHandle,
    state: &Mutex<ProxyState>,
    port: u16,
) -> anyhow::Result<()> {
    // --- check / update state ---
    {
        let mut s = state.lock().unwrap();
        if s.status == ProxyStatus::Running || s.status == ProxyStatus::Starting {
            anyhow::bail!("Proxy is already running on port {}", s.port);
        }
        s.port = port;
        s.status = ProxyStatus::Starting;
        let ev = snapshot(&s);
        emit_status(app_handle, ev);
    }

    // Helper: reset to Stopped on any error after we've already emitted Starting.
    // Also aborts any health-check task that may have been spawned before the error.
    let reset_on_err = |app: &AppHandle, state: &Mutex<ProxyState>, port: u16, msg: String| {
        let abort_tx = {
            let mut s = state.lock().unwrap();
            s.status = ProxyStatus::Stopped;
            s.child = None;
            s.health_task_abort.take()
        };
        // Abort orphaned health task if it was already spawned.
        if let Some(tx) = abort_tx {
            let _ = tx.send(());
        }
        emit_status(app, ProxyStatusEvent {
            status: ProxyStatus::Stopped,
            port,
            error: Some(msg),
        });
    };

    // --- generate proxy config ---
    let management_key = settings::read_settings()
        .map(|s| s.management_key)
        .unwrap_or_else(|_| "aether-managed".to_string());

    let config_path = match generate_proxy_config(port, &management_key) {
        Ok(p) => p,
        Err(e) => {
            let msg = format!("Failed to generate proxy config: {}", e);
            log::error!("{}", msg);
            reset_on_err(app_handle, state, port, msg.clone());
            anyhow::bail!(msg);
        }
    };
    let config_path_str = config_path
        .to_str()
        .ok_or_else(|| anyhow::anyhow!("Config path contains invalid UTF-8"))?
        .to_string();

    // --- spawn sidecar ---
    let cmd = match app_handle
        .shell()
        .sidecar("cliproxyapi")
        .map_err(|e| anyhow::anyhow!("Failed to create sidecar command: {}", e))
    {
        Ok(c) => c.args(["-config", &config_path_str]),
        Err(e) => {
            let msg = format!("Failed to create sidecar command: {}", e);
            log::error!("{}", msg);
            reset_on_err(app_handle, state, port, msg.clone());
            anyhow::bail!(msg);
        }
    };

    log::info!("Spawning CLIProxyAPI sidecar with args: -config {}", config_path_str);

    let (mut rx, child) = match cmd.spawn() {
        Ok(pair) => {
            log::info!("CLIProxyAPI sidecar spawned successfully (pid: {})", pair.1.pid());
            pair
        }
        Err(e) => {
            let msg = format!("Failed to spawn sidecar: {}", e);
            log::error!("{}", msg);
            reset_on_err(app_handle, state, port, msg.clone());
            anyhow::bail!(msg);
        }
    };

    // --- store child handle, reset stopping flag ---
    let stopping_flag = {
        let mut s = state.lock().unwrap();
        s.child = Some(child);
        s.stopping_flag.store(false, Ordering::SeqCst);
        Arc::clone(&s.stopping_flag)
    };

    // --- background task: watch for unexpected process exit ---
    {
        // Spawn the process-event listener. It owns `rx` exclusively.
        let app_exit = app_handle.clone();
        let stopping_flag_watcher = Arc::clone(&stopping_flag);
        tokio::spawn(async move {
            use tauri_plugin_shell::process::CommandEvent;
            loop {
                match rx.recv().await {
                    Some(CommandEvent::Terminated(payload)) => {
                        let code = payload.code;
                        if stopping_flag_watcher.load(Ordering::SeqCst) {
                            // Intentional stop — not a crash.
                            log::info!(
                                "CLIProxyAPI process stopped (code: {:?})",
                                code
                            );
                        } else {
                            log::warn!(
                                "CLIProxyAPI process terminated unexpectedly (code: {:?})",
                                code
                            );
                            // Signal crashed status — we can't update the Mutex here
                            // because we don't own the reference. We emit an event so
                            // the frontend (and any future health-check) can react.
                            if let Err(e) = app_exit.emit(
                                "proxy-status-changed",
                                ProxyStatusEvent {
                                    status: ProxyStatus::Crashed,
                                    port,
                                    error: Some(format!(
                                        "Process terminated with code {:?}",
                                        code
                                    )),
                                },
                            ) {
                                log::warn!("Failed to emit crash event: {}", e);
                            }
                        }
                        break;
                    }
                    Some(CommandEvent::Stdout(line)) => {
                        log::info!(
                            "cliproxyapi stdout: {}",
                            String::from_utf8_lossy(&line)
                        );
                    }
                    Some(CommandEvent::Stderr(line)) => {
                        log::info!(
                            "cliproxyapi stderr: {}",
                            String::from_utf8_lossy(&line)
                        );
                    }
                    None => {
                        // Channel closed — process finished.
                        break;
                    }
                    _ => {}
                }
            }
        });
    }

    // --- health check loop ---
    let (abort_tx, abort_rx) = tokio::sync::oneshot::channel::<()>();
    {
        let mut s = state.lock().unwrap();
        s.health_task_abort = Some(abort_tx);
    }

    let app_health = app_handle.clone();
    let stopping_flag_health = Arc::clone(&stopping_flag);
    tokio::spawn(async move {
        health_check_loop(app_health, port, abort_rx, stopping_flag_health).await;
    });

    Ok(())
}

/// Health-check loop that runs until the abort receiver fires.
///
/// On the **first** successful `/health` response the status is set to Running.
/// On failure **after** the proxy was Running, emit Crashed (unless `stopping_flag`
/// indicates an intentional stop) and exit the loop immediately — this prevents
/// the race condition where the health task and the process-exit watcher emit
/// conflicting status events.
async fn health_check_loop(
    app_handle: AppHandle,
    port: u16,
    mut abort_rx: tokio::sync::oneshot::Receiver<()>,
    stopping_flag: Arc<AtomicBool>,
) {
    let url = format!("http://localhost:{}/", port);
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(3))
        .build()
        .unwrap_or_default();

    let mut first_success = false;
    // Brief initial delay to let the sidecar bind its port.
    tokio::time::sleep(std::time::Duration::from_millis(500)).await;

    loop {
        tokio::select! {
            biased;
            _ = &mut abort_rx => {
                log::debug!("Health-check loop aborted for port {}", port);
                break;
            }
            result = client.get(&url).send() => {
                let healthy = result.map(|r| r.status().is_success()).unwrap_or(false);
                if healthy && !first_success {
                    first_success = true;
                    log::info!("CLIProxyAPI on port {} is healthy — status → Running", port);
                    if let Err(e) = app_handle.emit(
                        "proxy-status-changed",
                        ProxyStatusEvent {
                            status: ProxyStatus::Running,
                            port,
                            error: None,
                        },
                    ) {
                        log::warn!("Failed to emit running event: {}", e);
                    }
                } else if !healthy && first_success {
                    // Proxy was running but is now unreachable.
                    if stopping_flag.load(Ordering::SeqCst) {
                        // Intentional stop — the process-exit watcher handles the
                        // status transition; just exit cleanly.
                        log::debug!("Health check detected unreachable proxy during intentional stop (port {})", port);
                    } else {
                        log::warn!("CLIProxyAPI health check failed on port {} — emitting Crashed", port);
                        if let Err(e) = app_handle.emit(
                            "proxy-status-changed",
                            ProxyStatusEvent {
                                status: ProxyStatus::Crashed,
                                port,
                                error: Some(format!(
                                    "Proxy on port {} became unreachable",
                                    port
                                )),
                            },
                        ) {
                            log::warn!("Failed to emit crashed event: {}", e);
                        }
                    }
                    // Either way, exit the health loop — the proxy is gone.
                    break;
                }

                // Wait before next check.
                tokio::select! {
                    biased;
                    _ = &mut abort_rx => {
                        log::debug!("Health-check loop aborted (sleep phase) for port {}", port);
                        break;
                    }
                    _ = tokio::time::sleep(std::time::Duration::from_secs(10)) => {}
                }
            }
        }
    }
}

/// Stop the running proxy process.
pub async fn stop_proxy(
    app_handle: &AppHandle,
    state: &Mutex<ProxyState>,
) -> anyhow::Result<()> {
    let (child, port) = {
        let mut s = state.lock().unwrap();

        // Abort health-check task.
        if let Some(tx) = s.health_task_abort.take() {
            let _ = tx.send(());
        }

        // Signal the background watcher that this is an intentional stop.
        s.stopping_flag.store(true, Ordering::SeqCst);

        let port = s.port;
        let child = s.child.take();
        s.status = ProxyStatus::Stopped;

        (child, port)
    };

    if let Some(c) = child {
        if let Err(e) = c.kill() {
            log::warn!("Failed to kill CLIProxyAPI process: {}", e);
        }
    }

    emit_status(
        app_handle,
        ProxyStatusEvent {
            status: ProxyStatus::Stopped,
            port,
            error: None,
        },
    );

    Ok(())
}

/// Restart the proxy: stop → wait 500 ms → start.
pub async fn restart_proxy(
    app_handle: &AppHandle,
    state: &Mutex<ProxyState>,
    port: u16,
) -> anyhow::Result<()> {
    // Announce restart.
    {
        let mut s = state.lock().unwrap();
        s.status = ProxyStatus::Restarting;
        let ev = snapshot(&s);
        emit_status(app_handle, ev);
    }

    stop_proxy(app_handle, state).await?;
    tokio::time::sleep(std::time::Duration::from_millis(500)).await;
    start_proxy(app_handle, state, port).await?;

    Ok(())
}

/// Return a snapshot of the current proxy status.
pub fn get_proxy_status(state: &Mutex<ProxyState>) -> anyhow::Result<ProxyStatusEvent> {
    let s = state.lock().unwrap();
    Ok(snapshot(&s))
}
